**************************************************************************************************************
Filename: dna1.pdb
Date/time: Wed Aug 14 10:09:11 2024
Reference base-pair: 3.00
Zone: start 1 end 4
**************************************************************************************************************
Global bend angles of individual base-pair steps and of all identified base-pair steps together:
frac. tilt    = contribution of tilt to the base-pair step bending angle
frac. roll    = contribution of roll to the base-pair step bending angle
bp-step angle = bending angle (deg.) at each base-pair step.
orient angle  = orientation of the bend angle relative to the reference base-pair in Euler-angle
                space (from 0 to 360 deg.)
global tilt   = the value of Tilt (deg.) in the global reference frame.
global roll   = the value of Roll (deg.) in the global reference frame.
Acc. twist    = accumulated twist values (deg.) above and below the reference base-pair.
x	     = If the reference plane is located between two basepairs, one base-pair is
		       duplicated for the calculation (two x's). If the reference plane coincides with
		       one base-pair no duplication is necessary (one x)

index  bp-step  frac.tilt   frac.roll   bp-step angle orient angle global tilt  global roll  Acc.twist  refbp
 1       G-C      0.981       0.019        0.000       11.112         0.000        0.000       37.130    
 2       A-T      0.364       0.636        1.720       68.628         1.038        1.371       37.130    
 3       T-A      0.000       1.000        1.710       90.000         0.000        1.710        0.000   x
 4       C-G      0.364       0.636        1.710      111.365        -1.032        1.363      -37.130    

sum.              1.710       2.290        5.140      281.105         0.006        4.445       37.130
ave.              0.427       0.573        1.285       70.276         0.002        1.111        9.283
S.D.              0.172       0.172        0.005       17.447         0.845        0.162       30.317

The global bend-angle     = 4.445
**************************************************************************************************************
